[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-args=-o dist/rust.js -s USE_WEBGL2=1 --use-port=contrib.glfw3 -s MIN_WEBGL_VERSION=2 --preload-file suzane.obj -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s ASSERTIONS=1 -s ALLOW_MEMORY_GROWTH=1 -s EXPORTED_RUNTIME_METHODS=['ccall'] -s MODULARIZE=1 -s EXPORT_NAME='RustEMSModule'",
]